import type { MoveData } from './formula';

// Curated competitive moves with their canonical data.
// Grouped by category for the picker UI.
export const COMPETITIVE_MOVES: MoveData[] = [
  // ─── Physical · top picks ─────────────────────────────────────────────
  { name: 'Earthquake',     type: 'ground',  category: 'physical', basePower: 100 },
  { name: 'Close Combat',   type: 'fighting',category: 'physical', basePower: 120, tags: ['contact'] },
  { name: 'Stone Edge',     type: 'rock',    category: 'physical', basePower: 100 },
  { name: 'Rock Slide',     type: 'rock',    category: 'physical', basePower: 75 },
  { name: 'Iron Head',      type: 'steel',   category: 'physical', basePower: 80, tags: ['contact'] },
  { name: 'Crunch',         type: 'dark',    category: 'physical', basePower: 80, tags: ['bite', 'contact'] },
  { name: 'Outrage',        type: 'dragon',  category: 'physical', basePower: 120, tags: ['contact'] },
  { name: 'Dragon Claw',    type: 'dragon',  category: 'physical', basePower: 80, tags: ['contact'] },
  { name: 'Knock Off',      type: 'dark',    category: 'physical', basePower: 65, tags: ['contact'] },
  { name: 'U-turn',         type: 'bug',     category: 'physical', basePower: 70, tags: ['contact'] },
  { name: 'Bullet Punch',   type: 'steel',   category: 'physical', basePower: 40, priority: 1, tags: ['contact', 'punch', 'priority'] },
  { name: 'Mach Punch',     type: 'fighting',category: 'physical', basePower: 40, priority: 1, tags: ['contact', 'punch', 'priority'] },
  { name: 'Sucker Punch',   type: 'dark',    category: 'physical', basePower: 70, priority: 1, tags: ['contact', 'priority'] },
  { name: 'Extreme Speed',  type: 'normal',  category: 'physical', basePower: 80, priority: 2, tags: ['contact', 'priority'] },
  { name: 'Megahorn',       type: 'bug',     category: 'physical', basePower: 120, tags: ['contact'] },
  { name: 'Wave Crash',     type: 'water',   category: 'physical', basePower: 120, tags: ['contact', 'recoil'] },
  { name: 'Headlong Rush',  type: 'ground',  category: 'physical', basePower: 120, tags: ['contact'] },
  { name: 'Glaive Rush',    type: 'dragon',  category: 'physical', basePower: 120, tags: ['contact'] },
  { name: 'Ivy Cudgel',     type: 'grass',   category: 'physical', basePower: 100 },
  { name: 'Kowtow Cleave',  type: 'dark',    category: 'physical', basePower: 85, tags: ['contact'] },
  { name: 'Population Bomb',type: 'normal',  category: 'physical', basePower: 20, tags: ['contact', 'multi-hit'] },
  { name: 'Triple Axel',    type: 'ice',     category: 'physical', basePower: 20, tags: ['contact', 'multi-hit'] },
  { name: 'Ice Punch',      type: 'ice',     category: 'physical', basePower: 75, tags: ['contact', 'punch'] },
  { name: 'Fire Punch',     type: 'fire',    category: 'physical', basePower: 75, tags: ['contact', 'punch'] },
  { name: 'Thunder Punch',  type: 'electric',category: 'physical', basePower: 75, tags: ['contact', 'punch'] },
  { name: 'Play Rough',     type: 'fairy',   category: 'physical', basePower: 90, tags: ['contact'] },
  { name: 'Body Press',     type: 'fighting',category: 'physical', basePower: 80, tags: ['contact'] },
  { name: 'Aqua Jet',       type: 'water',   category: 'physical', basePower: 40, priority: 1, tags: ['contact', 'priority'] },
  { name: 'Flare Blitz',    type: 'fire',    category: 'physical', basePower: 120, tags: ['contact', 'recoil'] },
  { name: 'Ice Spinner',    type: 'ice',     category: 'physical', basePower: 80, tags: ['contact'] },
  { name: 'Liquidation',    type: 'water',   category: 'physical', basePower: 85, tags: ['contact'] },

  // ─── Special ──────────────────────────────────────────────────────────
  { name: 'Thunderbolt',    type: 'electric',category: 'special',  basePower: 90 },
  { name: 'Thunder',        type: 'electric',category: 'special',  basePower: 110, accuracy: 70 },
  { name: 'Ice Beam',       type: 'ice',     category: 'special',  basePower: 90 },
  { name: 'Blizzard',       type: 'ice',     category: 'special',  basePower: 110, accuracy: 70 },
  { name: 'Fire Blast',     type: 'fire',    category: 'special',  basePower: 110, accuracy: 85 },
  { name: 'Flamethrower',   type: 'fire',    category: 'special',  basePower: 90 },
  { name: 'Heat Wave',      type: 'fire',    category: 'special',  basePower: 95 },
  { name: 'Hydro Pump',     type: 'water',   category: 'special',  basePower: 110, accuracy: 80 },
  { name: 'Surf',           type: 'water',   category: 'special',  basePower: 90 },
  { name: 'Scald',          type: 'water',   category: 'special',  basePower: 80 },
  { name: 'Energy Ball',    type: 'grass',   category: 'special',  basePower: 90 },
  { name: 'Leaf Storm',     type: 'grass',   category: 'special',  basePower: 130 },
  { name: 'Giga Drain',     type: 'grass',   category: 'special',  basePower: 75 },
  { name: 'Sludge Bomb',    type: 'poison',  category: 'special',  basePower: 90 },
  { name: 'Sludge Wave',    type: 'poison',  category: 'special',  basePower: 95 },
  { name: 'Dazzling Gleam', type: 'fairy',   category: 'special',  basePower: 80 },
  { name: 'Moonblast',      type: 'fairy',   category: 'special',  basePower: 95 },
  { name: 'Aura Sphere',    type: 'fighting',category: 'special',  basePower: 80, tags: ['pulse'] },
  { name: 'Focus Blast',    type: 'fighting',category: 'special',  basePower: 120, accuracy: 70 },
  { name: 'Air Slash',      type: 'flying',  category: 'special',  basePower: 75 },
  { name: 'Hurricane',      type: 'flying',  category: 'special',  basePower: 110, accuracy: 70 },
  { name: 'Draco Meteor',   type: 'dragon',  category: 'special',  basePower: 130 },
  { name: 'Dragon Pulse',   type: 'dragon',  category: 'special',  basePower: 85, tags: ['pulse'] },
  { name: 'Shadow Ball',    type: 'ghost',   category: 'special',  basePower: 80 },
  { name: 'Hex',            type: 'ghost',   category: 'special',  basePower: 65 },
  { name: 'Dark Pulse',     type: 'dark',    category: 'special',  basePower: 80, tags: ['pulse'] },
  { name: 'Earth Power',    type: 'ground',  category: 'special',  basePower: 90 },
  { name: 'Flash Cannon',   type: 'steel',   category: 'special',  basePower: 80 },
  { name: 'Make It Rain',   type: 'steel',   category: 'special',  basePower: 120 },
  { name: 'Bug Buzz',       type: 'bug',     category: 'special',  basePower: 90, tags: ['sound'] },
  { name: 'Psychic',        type: 'psychic', category: 'special',  basePower: 90 },
  { name: 'Psyshock',       type: 'psychic', category: 'special',  basePower: 80 },
  { name: 'Power Gem',      type: 'rock',    category: 'special',  basePower: 80 },
  { name: 'Discharge',      type: 'electric',category: 'special',  basePower: 80 },
  { name: 'Volt Switch',    type: 'electric',category: 'special',  basePower: 70 },
  { name: 'Thunderclap',    type: 'electric',category: 'special',  basePower: 70, priority: 1, tags: ['priority'] },
  { name: 'Tera Blast',     type: 'normal',  category: 'physical', basePower: 80 },
];

export function findMove(name: string): MoveData | undefined {
  const n = name.toLowerCase();
  return COMPETITIVE_MOVES.find((m) => m.name.toLowerCase() === n);
}
